plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "google" # Or "numpy", "sphinx" - choose based on your preference
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_if_no_docstring: false
            show_category_heading: true
            show_bases: true
            heading_level: 2
            separate_signature: true

site_name: OptiSim Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Requirements: requirement.md
  - Installation: install.md
  - User Guide: user_guide.md
  - Developer Guide: dev_guide.md
  - Architecture: architecture.md
  - API Reference:
      - C++ Docs: api.md
      - Pythin Docs: python_api.md
  - Examples: examples.md
  - Video Tutorial: video.md
