plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "numpy" # Or "google", "sphinx" - choose based on your preference
            show_root_heading: false
            show_root_full_path: false
            show_object_full_path: false
            show_if_no_docstring: false
            show_category_heading: true
            show_bases: true
            heading_level: 2
            separate_signature: true
            show_source_link: false # This will hide the file path
            show_attributes: false


site_name: OptiSim Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Requirements: requirement.md
  - Installation: install.md
  - User Guide: user_guide.md
  - Developer Guide: dev_guide.md
  - Architecture: architecture.md
  - API Reference:
      - C++ Docs: api.md
      - Python Docs: python_api.md
  - Examples: examples.md
  - Video Tutorial: video.md
