site_name: OptiSim Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Requirements: requirement.md
  - Installation: install.md
  - User Guide: user_guide.md
  - Developer Guide: dev_guide.md
  - Architecture: architecture.md
  - API Reference:
      - C++ Docs: api.md
  - Examples: examples.md
  - Video Tutorial: video.md
